/* eslint-disable */
// Generated by Wrangler by running `wrangler types` (hash: 869ac3b4ce0f52ba3b2e0bc70c49089e)
// Runtime types generated with workerd@1.20250730.0 2025-08-02
declare namespace Cloudflare {
	interface Env {
		JINJYA_STORE: KVNamespace;
	}
}

export interface Env extends Cloudflare.Env {
	DB: any;
}
export {}

export const console = globalThis.console;
